### ISSUE TITLE
Corrigir a equação que fala sobre descobrir o indice do pai de um nó

### ISSUE THREAD

**Issue by andremedeiro** [joaoarthurbm/eda#38]
<p>Os nós 47 e 54 estão nos índices 3 e 4, respectivamente. Portanto, o nó pai está no índice 1, pois $int((3-1)/2)) = 1$ e $int((4-1)/2)) = 1$.</p>

**Comment by joaoarthurbm** [comment]
Oi, André. Dá mais detalhes, por favor. De qual material você está falando?

**Comment by joaoarthurbm** [comment]
E qual o erro, exatamente?

**Comment by andremedeiro** [comment]
Dentro da gh-pages, no post sobre Heap.

O texto enviado acima se trata do que seria a correção, pois no texto original a primeira equação sendo calculada resulta em 0

**Comment by joaoarthurbm** [comment]
Feito. Valeu! https://github.com/joaoarthurbm/eda/commit/0457a06f151215bcc4c0e49f35b421043c9027ff
