### ISSUE TITLE
Verificar o método add no material do linkedList

### ISSUE THREAD

**Issue by AndersonLLeite** [joaoarthurbm/eda#90]
No método add do material de LinkedList o seguinte trecho:
if (index == 0) {
        this.addFirst(valor);
        
    } else if (index == size - 1) {
        this.addLast(valor);
}
o parâmetro (valor)  do this.addFirst e this.addLast deveria ser (aluno) ?

**Comment by joaoarthurbm** [comment]
Obrigado!
